### ISSUE TITLE
Can't add products to cart

### ISSUE THREAD

**Issue by kilianyp** [tzyganu/EasylifeTag#2] opened 2014-09-28 03:36 UTC
Hi tzyganu,

first of all, thank you very much for the plugin, very helpful. I noticed I cannot add products to the cart anymore because the form key is wrong, which again has to do with the session. 
I tried to get my current session, but wasn't able to do so. It'd be awesome if you could provide a fix!

Thanks

**Comment by tzyganu** [comment] 2014-09-29 06:41
@kilsen512. Sorry but I cannot reproduce this issue. 
I think the extension has nothing to do with the form key. It just changes the url of the tag pages to `tag/tag-name-here` and routes those urls to the correct page. Nothing in the content is changed.  
You can disable the extension and see if the error reproduces.  
Also try it on the default theme. Maybe there is something wrong with your theme.
If the issue persists please provide more details about it.
I will close this for now, but if you can provide a scenario to reproduce the issue I will reopen it.

**Closed as completed by tzyganu** 2014-09-29 06:41 UTC

**Comment by kilianyp** [comment] 2014-10-13 12:36
You were right, the issue was caused by another plugin's router (amasty improved navigation). I don't understand why there was created a new session (debugging showed that session_hosts contained two 1s), but I got it to work now. 

Thank you for your answer!
